import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, BadgeCheck, Building2, ClipboardCheck, FileCheck2, Flame, Gauge, HardHat, Mail, Phone, ShieldCheck, Wrench } from 'lucide-react';
import { ContactForm } from '@/components/ContactForm';

const services = [
['Ley 6116 de Frente y Fachadas','Gestión de trámites vinculados a la normativa de frente y fachadas.',FileCheck2],['Habilitación de ascensores','Acompañamiento para habilitación y documentación de elevadores.',Building2],['Empresas conservadoras','Inscripción y renovación de empresas conservadoras.',ClipboardCheck],['Aviso de obras','Gestión del aviso y documentación necesaria para obras.',FileCheck2],['Vinculación en AGIP','Asistencia para la vinculación correspondiente en AGIP.',ShieldCheck],['Obleas de elevadores, térmicos e IFCI','Registro y renovación de obleas y documentación asociada.',Gauge],['Copia de planos','Gestión de copias de planos para la documentación requerida.',FileCheck2],['Automatización de calderas','Soluciones de automatización para instalaciones de calderas.',Flame],['Montajes de cañerías','Montajes e intervenciones sobre instalaciones de cañerías.',Wrench],['Montajes industriales','Montajes industriales y herrería de obra.',HardHat],['Calderas y tanques','Reparaciones e instalaciones de calderas y tanques.',Flame],['Calefacción y termografía','Trabajos de calefacción en general y servicios de termografía.',Wrench]
];
const faqs=[['¿Qué tipo de consultas puedo realizar?','Podés consultar por cualquiera de los trámites o servicios detallados en esta página. Si no sabés exactamente qué trámite corresponde, explicanos la situación y te orientamos.'],['¿Necesito tener toda la documentación antes de contactarlos?','No necesariamente. La idea es ayudarte a identificar qué documentación y pasos corresponden a tu caso antes de avanzar.'],['¿Atienden trámites y trabajos técnicos?','Sí. Gestoría AyS reúne gestión de trámites y servicios técnicos como calderas, tanques, calefacción, montajes y termografía.'],['¿Cómo solicito una cotización?','Completá el formulario de contacto con una descripción breve de lo que necesitás. También podés escribir por email o comunicarte telefónicamente.']];

export default function Home(){return <>
<section id="inicio" className="hero"><div className="hero-glow"/><div className="container hero-grid"><div className="hero-copy"><h1>Gestión profesional para <em>resolver con confianza</em></h1><p className="hero-lead">Acompañamos cada trámite y servicio técnico con organización, experiencia y una atención enfocada en encontrar soluciones concretas.</p><div className="hero-actions"><Link className="button button-primary" href="#contacto">Solicitar asesoramiento <ArrowRight size={18}/></Link><Link className="button button-ghost" href="#servicios">Ver servicios</Link></div><div className="hero-trust"><BadgeCheck size={18}/><span>Atención directa · Gestión clara · Respuesta personalizada</span></div></div><div className="hero-visual"><div className="image-ring"><Image src="/ays-notebook.svg" alt="Documentación y planificación de trámites" fill priority sizes="(max-width: 900px) 80vw, 45vw"/></div></div></div></section>
<section id="servicios" className="section services-section"><div className="container"><div className="section-heading"><div><span className="section-kicker">NUESTROS SERVICIOS</span><h2>Gestoría y servicios técnicos</h2><p className="services-intro">Desde habilitaciones y registros hasta instalaciones y servicios técnicos. Trabajamos sobre cada necesidad con una mirada práctica: entender el problema, ordenar la documentación y avanzar.</p></div></div><div className="service-grid">{services.map(([title,text,Icon])=><article className="service-card" key={title as string}><div className="service-icon"><Icon size={21}/></div><h3>{title as string}</h3><p>{text as string}</p><Link href="#contacto">Consultar <ArrowRight size={15}/></Link></article>)}</div></div></section>
<section id="proceso" className="section process-section"><div className="container process-grid"><div className="process-copy"><span className="section-kicker">CÓMO TRABAJAMOS</span><h2>Gestión clara, soluciones concretas</h2><p>No hace falta que conozcas de antemano cada paso administrativo o técnico. Partimos de tu necesidad y ordenamos el camino.</p><Link className="text-link" href="#contacto">Contanos qué necesitás resolver <ArrowRight size={17}/></Link></div><div className="steps">{['Contanos tu necesidad','Revisamos el caso','Ordenamos documentación y pasos','Avanzamos con la gestión o el trabajo'].map((step,i)=><div className="step" key={step}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{step}</h3><p>{['Por formulario, email o teléfono.','Identificamos qué corresponde y qué falta.','Te damos un camino claro para avanzar.','Te acompañamos hasta completar lo acordado.'][i]}</p></div></div>)}<div className="process-confidence"><div className="confidence-card"><ShieldCheck size={25}/><h3>Información clara</h3><p>Te explicamos qué se necesita y por qué, evitando pasos innecesarios.</p></div><div className="confidence-card"><ClipboardCheck size={25}/><h3>Gestión ordenada</h3><p>Documentación, trámites y servicios con seguimiento y criterio.</p></div><div className="confidence-card"><Wrench size={25}/><h3>Visión técnica</h3><p>Además de gestoría, contamos con servicios vinculados a instalaciones y mantenimiento.</p></div></div></div></div></section>
<section id="faq" className="section faq-section"><div className="container faq-grid"><div><span className="section-kicker">PREGUNTAS FRECUENTES</span><h2>Lo que necesitás saber antes de empezar</h2><p>Si tu pregunta no aparece acá, escribinos. Una consulta clara es un buen primer paso.</p></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
<section id="contacto" className="contact-section"><div className="container contact-grid"><div className="contact-copy"><span className="section-kicker">CONTACTO</span><h2>Contanos qué necesitás resolver</h2><p>Mandanos los datos básicos y una breve descripción. Te contactamos para orientarte sobre el trámite o servicio correspondiente.</p><div className="contact-details"><a href="https://api.whatsapp.com/send/?phone=5491156609916" target="_blank" rel="noopener noreferrer"><span><Phone size={18}/></span><div><small>WhatsApp</small><strong>+54 11 5660-9916</strong></div></a><a href="https://mail.google.com/mail/?view=cm&fs=1&to=ays.informes@gmail.com" target="_blank" rel="noopener noreferrer"><span><Mail size={18}/></span><div><small>Correo</small><strong>ays.informes@gmail.com</strong></div></a></div></div><ContactForm/></div></section>
</>}
