'use client';
import { useState, type FormEvent } from 'react';
import { CheckCircle2 } from 'lucide-react';

export function ContactForm(){
 const [sent,setSent]=useState(false); const [sending,setSending]=useState(false); const [error,setError]=useState(false);
 if(sent)return <div className="form-success"><CheckCircle2 size={42}/><h3>Consulta recibida</h3><p>Gracias por contactarte con Gestoría AyS. Vamos a revisar tu consulta y responderte por el medio indicado.</p></div>;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSending(true);setError(false);const form=e.currentTarget;try{const data=new FormData(form);const params=new URLSearchParams();data.forEach((value,key)=>params.append(key,typeof value==='string'?value:value.name));const response=await fetch('/__forms.html',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params.toString()});if(!response.ok)throw new Error('Form submission failed');setSent(true)}catch{setError(true)}finally{setSending(false)}}
 return <form className="contact-form" name="consultas" method="POST" action="/__forms.html" data-netlify="true" data-netlify-honeypot="bot-field" onSubmit={submit}><input type="hidden" name="form-name" value="consultas"/><p className="hidden-field"><label>No completar: <input name="bot-field"/></label></p><div className="form-row"><label>Nombre y apellido<input name="nombre" required placeholder="Tu nombre"/></label><label>Teléfono / WhatsApp<input name="telefono" required placeholder="11 1234-5678"/></label></div><div className="form-row"><label>Email<input type="email" name="email" required placeholder="tu@email.com"/></label><label>Servicio de interés<select name="servicio" defaultValue=""><option value="" disabled>Seleccioná una opción</option><option>Ley 6116 de Frente y Fachadas</option><option>Habilitación de ascensores</option><option>Empresas conservadoras</option><option>AGIP / Obleas / IFCI</option><option>Planos / Aviso de obras</option><option>Calderas / Tanques / Calefacción</option><option>Montajes / Herrería de obra</option><option>Termografía</option><option>Otro</option></select></label></div><label>Contanos brevemente qué necesitás<textarea name="mensaje" required rows={5} placeholder="Describí el trámite, instalación o problema que querés resolver..."/></label>{error&&<p role="alert" className="form-error">No pudimos enviar la consulta. Revisá tu conexión e intentá nuevamente.</p>}<button className="button button-primary" type="submit" disabled={sending}>{sending?'Enviando...':'Enviar consulta'}</button><small>Al enviar el formulario, tus datos se utilizan únicamente para responder tu consulta.</small></form>
}
